### ISSUE TITLE
关于MER任务以及音频部分的问题

### ISSUE THREAD

**Issue by zgMin** [MIPS-COLT/MER-MCE#1]
eval_ECAC_emotion.py是否是MER部分？我没有看到任何有关音频的处理和模型。

**Comment by MIPS-COLT** [comment]
eval_ECAC_emotion.py是我们之前使用大模型进行情绪识别的部分，因为效果一般，所以我们采取了其它方案，即我们论文中的第一阶段MER：使用attention融合不同模态的特征。

第一阶段的具体实现方法，我们参考的是以下仓库[MER2023](https://github.com/CASIA-Affective-Computing-Group/MER2023-Baseline)，其中关于有音频和图像的处理和模型。

**Comment by zgMin** [comment]
感谢解答疑惑Sent from my HONOR phone-------- Original message --------From: MIPS-COLT ***@***.***>Date: Sun, Apr 7, 2024, 10:20 AMTo: MIPS-COLT/MER-MCE ***@***.***>Cc: Leon ***@***.***>, Author ***@***.***>Subject: Re: [MIPS-COLT/MER-MCE] 关于MER任务以及音频部分的问题 (Issue #1)
eval_ECAC_emotion.py是我们之前使用大模型进行情绪识别的部分，因为效果一般，所以我们采取了其它方案，即我们论文中的第一阶段MER：使用attention融合不同模态的特征。
第一阶段的具体实现方法，我们参考的是以下仓库MER2023，其中关于有音频和图像的处理和模型。
