### ISSUE TITLE
可否提供下模型完整训练的流程，谢谢。README描述的不是很清楚。

### ISSUE THREAD

**Issue by redifinition** [MIPS-COLT/MER-MCE#4]

**Comment by ZebangCheng** [comment]
MCE训练部分步骤如下：
首先在**minigpt4/configs/datasets/firstface/ecac_emotion.yaml**文件中设置**ann_path**(我们将分享此文件到百度网盘和Google Drive中), 然后执行以下命令，即可开始训练：
`CUDA_VISIBLE_DEVICES=1,2,3 torchrun --nproc-per-node 3 train.py --cfg-path train_configs/minigptv2_finetune_exp.yaml`

更多的细节，我们将后在之后补充。

**Comment by Jesayy** [comment]
你好，这个文件在哪里提供/home/user/project/MER-MCE/checkpoints/minigptv2_checkpoint.pth

**Comment by ZebangCheng** [comment]
MiniGPT-v2官网的下载链接似乎已经失效，你可以从hugging face上下载，是一样的模型参数：
> Hugging Face Space Link](https://huggingface.co/spaces/Vision-CAIR/MiniGPT-v2/tree/main
